import { paginateOptions } from "../../constants/config";

export const ownerPayload = {
  create: {
    owner_id: "",
    corner_id: "",
    city_id: "",
    township_id: "",
    ward_id: "",
    street_id: "",
    land_no: "",
    house_no: "",
    property: "",
    meter_no: "",
    meter_bill_code: "",
  },
  update: {
    owner_id: "",
    corner_id: "",
    city_id: "",
    township_id: "",
    ward_id: "",
    street_id: "",
    land_no: "",
    house_no: "",
    property: "",
    meter_no: "",
    meter_bill_code: "",
  },
  delete: {
    owner_id: "",
    deleted_by: "",
    reason: "",
  },
  columns: [
    {
      field: "index",
      header: "No",
      sortable: false,
      show: true,
      width: 100,
      frozen: false,
    },
    {
      field: "owner_id",
      header: "Owner ID",
      sortable: true,
      show: true,
      width: 250,
      frozen: true,
    },
    {
      field: "property",
      header: "Property Type",
      sortable: true,
      show: true,
      width: 250,
      frozen: false,
    },
    {
      field: "status",
      header: "Status",
      sortable: true,
      show: true,
      width: 250,
      frozen: false,
    },
    {
      field: "corner_id",
      header: "Corner ID",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "city_id",
      header: "City ID",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "township_id",
      header: "Township ID",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "ward_id",
      header: "Ward ID",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "street_id",
      header: "Street ID",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "wifi_id",
      header: "WiFi ID",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "land_no",
      header: "Land No.",
      sortable: true,
      show: true,
      width: 200,
    },
    {
      field: "house_no",
      header: "House No.",
      sortable: true,
      show: true,
      width: 200,
    },
    {
      field: "meter_no",
      header: "Meter No.",
      sortable: true,
      show: true,
      width: 200,
    },
    {
      field: "meter_bill_code",
      header: "Meter Bill Code",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "wifi_user_id",
      header: "WiFi User ID",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "land_id",
      header: "Land ID",
      sortable: true,
      show: true,
      width: 200,
    },
    {
      field: "issuance_date",
      header: "Issuance Date",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "expired",
      header: "Expiration Date",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "renter_id",
      header: "Renter ID",
      sortable: true,
      show: true,
      width: 200,
    },
    {
      field: "contract_date",
      header: "Contract Date",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "end_of_contract_date",
      header: "End of Contract",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "price_per_month",
      header: "Monthly Price",
      sortable: true,
      show: true,
      width: 250,
    },
    {
      field: "total_months",
      header: "Total Months",
      sortable: true,
      show: true,
      width: 200,
    },
    { field: "notes", header: "Notes", sortable: true, show: true, width: 300 },
    {
      field: "photos",
      header: "Photos",
      sortable: true,
      show: true,
      width: 300,
    },
  ],

  paginateParams: {
    page: 1,
    per_page: paginateOptions.rows,
    columns:
      "id,owner_id,corner_id,city_id,township_id,ward_id,street_id,wifi_id,land_no,house_no,property,meter_no,meter_bill_code,wifi_user_id,land_id,issuance_date,expired,renter_id,contract_date,end_of_contract_date,price_per_month,total_months,notes,photos",
    search: "",
    order: "id",
    sort: "DESC",
    filter: "status",
  },
};
